remote_theme: "mmistakes/minimal-mistakes@4.24.0"
skin: dark
title: RollingScones - Projects
description: Complete post 2023 documentaion of all my projects

base_url: https://github.com/RollingScones/RollingScones
repository: RollingScones/RollingScones

# Minima social links
github_username: RollingScones

rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE

